#!/usr/bin/env bash

monthNumToName() {
	case $1 in
	1) month="Jan" ;; 2) month="Feb" ;;
	3) month="Mar" ;; 4) month="Apr" ;;
	5) month="May" ;; 6) month="Jun" ;;
	7) month="Jul" ;; 8) month="Aug" ;;
	9) month="Sep" ;; 10) month="Oct" ;;
	11) month="Nov" ;; 12) month="Dec" ;;
	*) echo "$0: Unknown month value $1" >&2 ;;
	esac
	return 0
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
	if [ $# -ne 3 ]; then
		cat >&2 <<EOF
"Usage: $0 month day year
Formats are August 3 1962 and 8 3 1962"
EOF
		exit 1
	fi

	if [ "$3" -le 999 ]; then
		cat <&2 <<EOF
"$0: expected 4-digit year value."
EOF
		exit 1
	fi

	if [ -z "$(echo "$1" | sed 's/[[:digit:]]//g')" ]; then
		monthNumToName "$1"
	else
		if [ ${#1} -lt 3 ]; then
			cat >&2 <<EOF
"Usage: $0 month day year
Formats are August 3 1962 and 8 3 1962"
EOF
			exit 1
		elif [ ${#1} -eq 3 ]; then
			month="$(echo "${1%${1#?}}" | tr '[:lower:]' '[:upper:]')"
			month=$month$(echo "$1" | cut -c 2-3 | tr '[:upper:]' '[:lower:]')
		else
			case $(echo "$1" | tr '[:upper:]' '[:lower]') in
			january) month="Jan" ;;
			march) month="Mar" ;;
			may) month="May" ;;
			july) month="Jul" ;;
			september) month="Sep" ;;
			november) month="Nov" ;;
			february) month="Feb" ;;
			april) month="Apr" ;;
			june) month="Jun" ;;
			augest) month="Aug" ;;
			october) month="Oct" ;;
			december) month="Dec" ;;
			*)
				cat >&2 <<EOF
"Usage: $0 month day year
Formats are August 3 1962 , Aug 3 1962 and 8 3 1962"
EOF
				exit 1
				;;

			esac

		fi

	fi

	echo "$month" "$2" "$3"
fi
