#!/usr/bin/env bash

width=72

for input; do
	lines="$(wc -l <"$input" | sed 's/ //g')"
	chars="$(wc -c <"$input" | sed 's/ //g')"
	owner="$(ls -ld "$input" | awk '{ print $3 }')"

	cat <<EOF
"---------------------------------------------------------------
  File $input ($lines lines, $chars characters, owned by $owner):
 ---------------------------------------------------------------"
EOF

	while read -r line; do
		if [ ${#line} -gt $width ]; then
			echo "$line" | fmt | sed -e '1s/^/ /' -e '2,$s/^/+ /'
		else
			echo " $line"
		fi
	done <"$input"

	echo "---------------------------------------------------------------"
done | ${PAGER:=less}

exit 0
