#!/usr/bin/env bash

archivedir="$HOME/.deleted_files"
realrm="$(which rm)"
move="$(which mv)"
ls="$(which ls)"

dest=$(pwd)
deletecopies=false
restorelatest=false

if [ ! -d "$archivedir" ] || [ -z "$($ls -A "$archivedir")" ]; then
	echo "$0: No deleted files to unrm" >&2
	exit 1
fi

cd "$archivedir"

while getopts "Dl" opt; do
	case $opt in
	D) deletecopies=true ;;
	l) restorelatest=true ;;
	*) ;;

	esac
done
shift $(("$OPTIND" - 1))

if [ $# -eq 0 ]; then
	echo "Contents of your deleted files archive (sorted by date):"
	$ls -FC | sed -e 's/\([[:digit:]][[:digit:]]\.\)\{5\}//g' -e 's/^/ /'
	exit 0
fi

matches="$($ls -d ./*"$1" 2>/dev/null | wc -l)"
if [ "$matches" -eq 0 ]; then
	echo "No match for \"$1\" in the deleted file archive." >&2
	exit 1
fi

if [ "$matches" -gt 1 ]; then
	echo "More than one file or directory match in the archive"
	index=1
	# for name in $($ls -td ./*"$1"); do
	for name in $($ls -td ./??.??.??.??.??."$1"); do
		datetime="$(echo "$name" | cut -c1-14 |
			awk -F. '{print $5"/"$4" at "$3":"$2":"$1 }')"
		filename="$(echo "$name" | cut -c16-)"
		if [ -d "$name" ]; then
			filecount="$($ls "$name" | wc -l | sed 's/[^[:digit:]]//g')"
			echo " $index) $filename (contents = ${filecount} items, " \
				" deleted = $datetime)"
		else
			size="$($ls -sdk1 "$name" | awk '{ print $1 }')"
			echo " $index) $filename (size = ${size}Kb, deleted = $datetime)"
		fi
		index=$((index + 1))
	done
	if [ $restorelatest = false ]; then
		echo ""
		read -r -p "Which version of $1 should I restore ( '0' to quit )? [1] : " desired
		if [ -n "$(echo $desired | sed 's/[[:digit:]]//g')" ]; then
			echo "$0 Restore canceled by user: invalid input." >&2
			exit 1
		fi
		if [ ${desired:=1} -ge $index ]; then
			echo "$0: Restore canceled by user: index value too big." >&2
			exit 1
		fi
		if [ $desired -lt 1 ]; then
			echo "$0: Restore canceled by user." >&2
			exit 1
		fi

		restore="$($ls -td1 ./*"$1" | sed -n "${desired}p")"
	else
		restore="$($ls -td1 ./*"$1" | head -n 1)"
	fi

	if [ -e "$dest/$1" ]; then
		echo "\"$1\ already exists in this directory. Cannot overwrite." >&2
		exit 1
	fi

	/bin/echo -n "Restoring file \"$1\" ..."
	$move "$restore" "$dest/$1"
	echo "done."

	if [ $deletecopies = false ]; then
		read -r -p "Delete the additional copies of this file [y] " answer

		if [ "${answer:=y}" = 'y' ]; then
			$realrm -rf "$archivedir"/*"$1"
			echo "Deleted."
		else
			echo "Additional copies retained"
		fi
	else
		$realrm -rf "$archivedir"/*"$1"
	fi
else
	if [ -e "$dest/$1" ]; then
		echo "\"$1\ already exists. Cannot overwrite" >&2
		exit 1
	fi

	restore="$(ls -d ./*"$1")"

	/bin/echo -n "Restoring file \"$1\" ..."
	$move "$restore" "$dest/$1"
	echo "Done."
fi

exit 0
