#!/usr/bin/env bash

IFS=":"
count=0
nonex=0
for directory in $PATH; do
	# echo "$directory"
	if [ -d "$directory" ]; then
		for command in "$directory"/*; do
			echo "$command"
			if [ -x "$command" ]; then
				count=$((count + 1))
			else
				nonex=$((nonex + 1))
			fi
		done
	fi
done

echo "Executable: $count"
echo "Nonexecutable: $nonex"
