#!/usr/bin/env bash

chosen=$(cut -d ';' -f1 "$HOME/dox/emoji" |
	dmenu -i -l 20 -nb '#282828' -sf '#fabd2f' -sb '#504945' -nf '#a89984' |
	sed "s/ .*//")

#Exit if none chosen
[ -z "$chosen" ] && exit

if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard"
fi
