#!/usr/bin/env bash

DIRECTORY="$HOME/dox/books/"

if [[ -d $DIRECTORY ]]; then
	CHOSENBOOK=$(/bin/ls -A "$DIRECTORY" |
		sed -e 's/\.[[:alpha:]]*$//' |
		dmenu -i -l 15 -p \
			"What to read..." -nb '#282828' -sf '#fabd2f' -sb '#504945' -nf '#a89984' -fn 'Mononoki Nerd Font:bold:pixelsize=13')
	if [[ $CHOSENBOOK ]]; then
		zathura "$DIRECTORY"/"$CHOSENBOOK".*
	else
		notify-send "💣 Error during oppening the book"
	fi
else
	notify-send "💣 Directory doesn't exist"
fi
