#!/usr/bin/env bash

options=("search
random
quit")

choice=$(echo -e "${options[@]}" |
	dmenu -i -p "Manpages..." -nb '#282828' -sf '#fabd2f' -sb '#504945' -nf '#a89984' -fn 'Mononoki Nerd Font:bold:pixelsize=13')

case $choice in
quit)
	notify-send "💣 Program terminated"
	;;
search)
	man -k . | shuf |
		dmenu -i -l 20 -p "What man to read..." -nb '#282828' -sf '#fabd2f' -sb '#504945' -nf '#a89984' -fn 'Mononoki Nerd Font:bold:pixelsize=13' |
		awk '{print $1}' |
		xargs -r man -Tpdf | zathura -
	;;
random)
	find /usr/share/man/man1 -type f | shuf |
		awk -F '/' '/1/ {print $6}' |
		sed 's/.gz//g' | head -1 |
		dmenu -i -p "Random Manpage..." -nb '#282828' -sf '#fabd2f' -sb '#504945' -nf '#a89984' -fn 'Mononoki Nerd Font:bold:pixelsize=13' |
		xargs man -Tpdf | zathura -
	;;
esac
