#!/usr/bin/env bash

IMG=$(basename "$1")
IMGNAME="${IMG%.*}"

# set wallpaper
feh --bg-fill "$1"
echo "feh --bg-fill $1" >>~/.config/awesome/autostart.sh

# wal itself
echo "Checking if pywal is installed..."
if ! pacman -Qi python-pywal; then
	echo "Installing pywal"
	sudo pacman -S --noconfirm python-pywal
fi
echo "Runnging pywal with $IMGNAME..."
wal -i "$1"
# TODO add check for window manager
echo "Adding wal theme to awesome autostart..."
echo "wal -R" >>~/.config/awesome/autostart.sh

# awesome
echo "Setting wal colors for awesomewm..."
~/scripts/awesomewal
echo "Restarting awesome..."
ecoh 'awesome.restart()' | awesomeclient

# GTK theme
echo "Checking if oomox is installed..."
if ! pacman -Qi oomox; then
	echo "Installing oomox..."
	yay -S --noconfirm --answerdiff=None oomox
fi
echo "Configuring gtk themes..."
/opt/oomox/plugins/theme_oomox/gtk-theme/change_color.sh -o wal-oomox-"$IMGNAME" -m all -d true --hidpi --true ~/.cache/wal/colors-oomox
echo "Configuring icons..."
/opt/oomox/plugins/icons_gnomecolors/gnome-colors-icon-theme/change_color.sh -o wal-oomox-icons-"$IMGNAME" ~/.cache/wal/colors-oomox
echo "Oppening lxpappearance to apply theme and icons..."
lxappearance

# firefox
echo "Checking if pywalfox is installed..."
if ! pip show pywalfox; then
	echo "Installing pywalfox..."
	pip install pywalfox
fi
echo "Chmoddinx pywalfox executable..."
sudo chmod +x ~/.local/lib/python3.8/site-packages/pywalfox/bin/main.sh
echo "Setuping pywalfox..."
pywalfox setup
echo "Running pywalfox daemon..."
pywalfox daemon &
echo "Now install firefox extension and fetch pywal colors..."
firefox https://addons.mozilla.org/en-US/firefox/addon/pywalfox/?src=search

# telegram
echo "Clonning telegram-palette-gen repo..."
git clone --depth 1 https://github.com/matteoguarda/telegram-palette-gen ~/.telegram-palette-gen
echo "Generating theme for telegram..."
~/.telegram-palette-gen/telegram-palette-gen --wal
echo "Openning telegram to apply theme..."
telegram-desktop
